title: felixbaral.github.io
url: "https://felixbaral.github.io"
freelancestatus_text: "ğŸŸ¢ Available for freelance work (âœï¸ May 2020)"
freelancestatus: true
baseurl: "/"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

theme: jekyll-theme-cayman
